esphome:
  name: "esphome-velador"
  friendly_name: "velador"

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret velador_hassio_key

ota:
  - platform: esphome
    password: !secret ota_password
  

status_led:
  pin:
    number: D0
    inverted: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

light:
  - platform: neopixelbus
    id: velador
    type: RGB
    variant: WS2811
    pin: D2
    num_leds: 50
    name: "led"
    flash_transition_length: 100ms
    effects:
      - addressable_rainbow:

#sensor:
#  - platform: dht
#    pin: D1
#    temperature:
#      name: "Temperatura Habitacion"
#    humidity:
#      name: "Humedad Habitacion"
#    update_interval: 180s

binary_sensor:
  - platform: gpio
    pin:
      number: D3
      inverted: True
      mode:
        input: true
        pullup: True
    name: "Power light"
    filters:
      - delayed_on: 10ms
    on_press:
      - if:
          condition:
            light.is_off: velador
          then:
            - light.turn_on:
                id: velador
                brightness: 45%
                red: 100%
                green: 100%
                blue: 100%
          else:
            - light.turn_off: velador
          
    on_double_click:
      - light.turn_on:
          id: velador
          brightness: 45%
          red: 54%
          green: 24%
          blue: 81%