name: Build ledfx and push to docker hub
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (M.m.p)
        required: true

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: podman/ledfx
            file: podman/ledfx/Dockerfile
            build-args: |
              LEDFX_VERSION=${{github.event.inputs.version}}
            push: true
            tags: |
              gerulrich/ledfx:${{github.event.inputs.version}},
              gerulrich/ledfx:latest
            platforms: linux/amd64,linux/arm64